// <auto-generated />
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Synchronization")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Palmmedia")]
[assembly: AssemblyProduct("MetroBackUp")]
[assembly: AssemblyCopyright("Copyright © Palmmedia 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("f8892c01-ffd6-4911-adb5-a485a43873b3")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Palmmedia.BackUp.Synchronization.Test")]
// [assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Palmmedia.BackUp.Synchronization.Test, PublicKey=0024000004800000940000000602000000240000525341310004000001000100B91139722596358820A6E216832C62846EE9055F7A275A977A0F7D117930CB51578CC8B9F450AA43435AA4B170C69E0187349FD27BF8548259FFA3C96C39D20356FAF83191BD3CFBAE11F6CB80537572D12432F176AC3E0019FFA3E0E45C7A1E28206AE1B394054C8C930752AB035199573008C283B7E44BFA61EE80DE0971B5")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: CLSCompliant(true)]