//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palmmedia.BackUp.SharedResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palmmedia.BackUp.SharedResources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created directories.
        /// </summary>
        public static string CreateDirectoriesSuccess {
            get {
                return ResourceManager.GetString("CreateDirectoriesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copied files.
        /// </summary>
        public static string CreateFilesSuccess {
            get {
                return ResourceManager.GetString("CreateFilesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted directories.
        /// </summary>
        public static string DeleteDirectoriesSuccess {
            get {
                return ResourceManager.GetString("DeleteDirectoriesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted files.
        /// </summary>
        public static string DeleteFilesSuccess {
            get {
                return ResourceManager.GetString("DeleteFilesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logfile.
        /// </summary>
        public static string Logfile {
            get {
                return ResourceManager.GetString("Logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Directory.
        /// </summary>
        public static string ReferenceDirectory {
            get {
                return ResourceManager.GetString("ReferenceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize in both directions.
        /// </summary>
        public static string SyncModeType_BothWays {
            get {
                return ResourceManager.GetString("SyncModeType_BothWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Reference Directory.
        /// </summary>
        public static string SyncModeType_LeftToRight {
            get {
                return ResourceManager.GetString("SyncModeType_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror Reference Directory (without deleting files).
        /// </summary>
        public static string SyncModeType_LeftToRightWithoutDeletion {
            get {
                return ResourceManager.GetString("SyncModeType_LeftToRightWithoutDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Directory.
        /// </summary>
        public static string TargetDirectory {
            get {
                return ResourceManager.GetString("TargetDirectory", resourceCulture);
            }
        }
    }
}
